// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGq0_PjYgzjm36jTQGcJUEpASKJCiwoh4',
    appId: '1:363283655628:web:e925ce143be5f508a38b69',
    messagingSenderId: '363283655628',
    projectId: 'finbot-6fc9b',
    authDomain: 'finbot-6fc9b.firebaseapp.com',
    databaseURL: 'https://finbot-6fc9b-default-rtdb.firebaseio.com',
    storageBucket: 'finbot-6fc9b.appspot.com',
    measurementId: 'G-Y2RH5YWML8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe84Nza_v5vlN5tMKBw2GaZVD19yfgAhY',
    appId: '1:363283655628:android:4d906b786c06fc2da38b69',
    messagingSenderId: '363283655628',
    projectId: 'finbot-6fc9b',
    databaseURL: 'https://finbot-6fc9b-default-rtdb.firebaseio.com',
    storageBucket: 'finbot-6fc9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAynys7qmweJk62UvevMXy0hmdbAKcsCs0',
    appId: '1:363283655628:ios:1f4ca571e52a9f36a38b69',
    messagingSenderId: '363283655628',
    projectId: 'finbot-6fc9b',
    databaseURL: 'https://finbot-6fc9b-default-rtdb.firebaseio.com',
    storageBucket: 'finbot-6fc9b.appspot.com',
    iosBundleId: 'com.example.budgetBuddy2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAynys7qmweJk62UvevMXy0hmdbAKcsCs0',
    appId: '1:363283655628:ios:c9010fd516149bd8a38b69',
    messagingSenderId: '363283655628',
    projectId: 'finbot-6fc9b',
    databaseURL: 'https://finbot-6fc9b-default-rtdb.firebaseio.com',
    storageBucket: 'finbot-6fc9b.appspot.com',
    iosBundleId: 'com.example.budgetBuddy2.RunnerTests',
  );
}
